description: |-
  This playbook blocks malicious URLs using all integrations that you have enabled.

  Supported integrations for this playbook:
  * Palo Alto Networks Minemeld
  * Zscaler
id: block_url_-_generic
inputs:
- description: The name of the URL blacklist Miner in  Minemeld.
  key: URLBlacklistMiner
  required: false
  value: {}
- description: Array of malicious URLs to block.
  key: URL
  required: false
  value: {}
name: Block URL - Generic
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: b95110b7-ba18-42a5-87ad-c5d37915401c
      iscommand: false
      name: ""
      version: -1
    taskid: b95110b7-ba18-42a5-87ad-c5d37915401c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 40
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ""
      id: 1808d949-f921-4957-8796-7bbedd822ad9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 1808d949-f921-4957-8796-7bbedd822ad9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -80,
          "y": 900
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
      - "12"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: f414f4c2-03f8-4219-8428-048557b1758b
      iscommand: false
      name: Block URLs
      type: title
      version: -1
    taskid: f414f4c2-03f8-4219-8428-048557b1758b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 370
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.URL
          operator: isExists
      label: "yes"
    id: "8"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "5"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Verify that the playbook input includes at least one URL to block.
      id: ad6bb4b2-ea87-4c6e-893c-a31e27e82e55
      iscommand: false
      name: Is there a URL to block?
      type: condition
      version: -1
    taskid: ad6bb4b2-ea87-4c6e-893c-a31e27e82e55
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 175
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    scriptarguments:
      Indicator:
        complex:
          root: inputs.URL
      MinerName:
        complex:
          root: inputs.URLBlacklistMiner
    separatecontext: true
    task:
      brand: ""
      id: 2d0fc7d4-b827-43c9-8b7a-bf592e7a1c1f
      iscommand: false
      name: Add Indicator to Miner - Minemeld
      playbookId: add_indicator_to_miner_-_palo_alto_mineMeld
      type: playbook
      version: -1
    taskid: 2d0fc7d4-b827-43c9-8b7a-bf592e7a1c1f
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 150,
          "y": 550
        }
      }
  "12":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Zscaler
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "12"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "13"
    note: false
    separatecontext: false
    task:
      brand: ""
      description: Verify that there is a valid instance of Zscaler enabled.
      id: a2108a1a-7365-45e7-8c07-a5a6fcdd8b95
      iscommand: false
      name: Is Zscaler enabled?
      type: condition
      version: -1
    taskid: a2108a1a-7365-45e7-8c07-a5a6fcdd8b95
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 610,
          "y": 550
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    scriptarguments:
      url:
        complex:
          root: inputs.URL
    separatecontext: false
    task:
      brand: ""
      description: Block the URLS using Zscaler.
      id: adb7b441-33c8-4fe9-8883-7af9a776e0d3
      iscommand: true
      name: Block URL with Zscaler
      script: '|||zscaler-blacklist-url'
      type: regular
      version: -1
    taskid: adb7b441-33c8-4fe9-8883-7af9a776e0d3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 610,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 925,
        "width": 1070,
        "x": -80,
        "y": 40
      }
    }
  }
